services:

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - ${DOCKER_DATA_PATH}/neo4j/logs:/logs
      - ${DOCKER_DATA_PATH}/neo4j/config:/config
      - ${DOCKER_DATA_PATH}/neo4j/data:/data
      - ${DOCKER_DATA_PATH}/neo4j/plugins:/plugins
      - ${DOCKER_DATA_PATH}/neo4j/import:/import
      - ${EXPORT_DIR}:/import/exports
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: wget -O /dev/null "http://localhost:7474/" || exit 1
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 30s

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cwaf
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_DATA_PATH}/postgres:/var/lib/postgresql/data
      - ${EXPORT_DIR}:/exports
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
        restart: true


  fastapi:
    container_name: fastapi
    build: 
      dockerfile: fastapi_dockerfile
      context: ./docker
    volumes:
      - ${PWD}/.env:/app/.env
      - ${WEB_APP_PATH}:/app
      - ${DOCKER_DATA_PATH}/shared:/shared
      - ${EXPORT_DIR}:/exports
    working_dir: /app
    ports:
      - "8000:8000"
    command: "uvicorn api:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
      waf:
        condition: service_started
        restart: true

  streamlit:
    container_name: streamlit
    build: 
      dockerfile: streamlit_dockerfile
      context: ./docker
    volumes:
      - ${WEB_APP_PATH}:/app
      - ${DOCKER_DATA_PATH}/shared:/shared
    working_dir: /app
    ports:
      - "8501:8501"
    entrypoint: "streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0"
    depends_on:
      fastapi:
        condition: service_started
        restart: true

  waf:
    container_name: waf
    build:
      dockerfile: waf_dockerfile
      context: ./docker
    privileged: true
    volumes:
      - ${SRC_PATH}/waf_rest_api:/opt/api
    ports:
      - "9090:8000"
    working_dir: /opt/api
    command: "fastapi dev main.py --host 0.0.0.0 --port 8000"

  parser:
    container_name: parser
    build:
      dockerfile: parser_dockerfile
      context: ./docker
    volumes:
      - ${SRC_PATH}/parser:/app
      - ${PWD}/.env:/app/.env
    ports:
      - "8001:8000" 
    environment:
      - RUNNING_IN_DOCKER=true
    working_dir: /app
    tty: true
    command: "fastapi dev rest_api/api.py --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
          condition: service_healthy
          restart: true


  chatbot:
    container_name: chatbot
    build: 
      dockerfile: chatbot_dockerfile
      context: ./docker
    volumes:
      - ${PWD}/.env:/app/.env
      - ${CHATBOT_PATH}:/app
      - ${DOCKER_DATA_PATH}/chromadb:/chromadb
    working_dir: /app
    ports:
      - "8005:8005"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      fastapi:
        condition: service_started
      neo4j:
        condition: service_started
      postgres:
        condition: service_started
      streamlit:
        condition: service_started
    entrypoint: "/start_chat.sh"