services:

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    volumes:
      - ${DOCKER_DATA_PATH}/neo4j/logs:/logs
      - ${DOCKER_DATA_PATH}/neo4j/config:/config
      - ${DOCKER_DATA_PATH}/neo4j/data:/data
      - ${DOCKER_DATA_PATH}/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: wget -O /dev/null "http://localhost:7474/" || exit 1
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 30s

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cwaf
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_DATA_PATH}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
        restart: true


  fastapi:
    container_name: fastapi
    build: 
      dockerfile: fastapi_dockerfile
      context: ./docker
    volumes:
      - ${PWD}/.env:/app/.env
      - ${WEB_APP_PATH}:/app
      - ${DOCKER_DATA_PATH}/shared:/shared
    working_dir: /app
    ports:
      - "8000:8000"
    command: "uvicorn api:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
      waf:
        condition: service_started
        restart: true

  streamlit:
    container_name: streamlit
    build: 
      dockerfile: streamlit_dockerfile
      context: ./docker
    volumes:
      - ${WEB_APP_PATH}:/app
      - ${DOCKER_DATA_PATH}/shared:/shared
    working_dir: /app
    ports:
      - "8501:8501"
    entrypoint: "streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0"
    depends_on:
      fastapi:
        condition: service_started
        restart: true

  waf:
    container_name: waf
    build:
      dockerfile: waf_dockerfile
      context: ./docker
    privileged: true
    volumes:
      - ${SRC_PATH}/waf_rest_api:/opt/api
    ports:
      - "9090:8000"
    working_dir: /opt/api
    command: "fastapi dev main.py --host 0.0.0.0 --port 8000"